/**
 * GENERATED by scripts/design-system/generate-gallery-manifest.mjs — do not edit.
 * @file galleryManifest.ts
 * @description Generated manifest of every atom gallery entry, in
 * alphabetical order. Consumed by the /playground route and the
 * design-system/gallery-manifest-fresh lint rule (eslint.config.local.ts).
 * Regenerate with: node scripts/design-system/generate-gallery-manifest.mjs
 * @module components/atoms/galleryManifest
 */
import { gallery as boxGallery } from "./Box/gallery";
import { gallery as buttonGallery } from "./Button/gallery";
import { gallery as centerGallery } from "./Center/gallery";
import { gallery as dividerGallery } from "./Divider/gallery";
import { gallery as headingGallery } from "./Heading/gallery";
import { gallery as iconGallery } from "./Icon/gallery";
import { gallery as inputGallery } from "./Input/gallery";
import { gallery as pressableGallery } from "./Pressable/gallery";
import { gallery as scrollViewGallery } from "./ScrollView/gallery";
import { gallery as spinnerGallery } from "./Spinner/gallery";
import { gallery as stackGallery } from "./Stack/gallery";
import { gallery as textGallery } from "./Text/gallery";

import type { GalleryEntry } from "./galleryTypes";

export const galleryManifest: readonly GalleryEntry[] = [
  boxGallery,
  buttonGallery,
  centerGallery,
  dividerGallery,
  headingGallery,
  iconGallery,
  inputGallery,
  pressableGallery,
  scrollViewGallery,
  spinnerGallery,
  stackGallery,
  textGallery,
];
